### ISSUE TITLE
Plugin does not log login attemps

### ISSUE THREAD

**Issue by leucos** [splitbrain/dokuwiki-plugin-loglog#31]
Unless I messed up something, it seems the plugin does not log **failed** loggin attempts.
Logins & logouts are properly logged.

Using: LogLog 2017-02-08 with 2017-02-19b "Frusterick Manners"

**Comment by leucos** [comment]
Oh, just saw that this plugin is not marked compatible with my Dokuwiki version

"Detritus" (2015-08-10), "Hrun" (2014-09-29)

Sorry for the noise.

**Comment by splitbrain** [comment]
what auth backend do you use?

**Comment by leucos** [comment]
@splitbrain I use authplain

**Comment by moisesbr-dw** [comment]
@splitbrain please merge my pull request. It's 3 years old already...
