### ISSUE TITLE
Not log failed loggin attempts.

### ISSUE THREAD

**Issue by Franck2A** [splitbrain/dokuwiki-plugin-loglog#36]
Hello,
I'm on Greebo for two dokuwiki instances, the first use auth-ldap plugin and the second one use auth-plain plugin.
For both, i don't see failed loggin attempts in /data/cache/loglog.log .
I may have missed some things ?
Tnx for help and best regards.
Franck

**Comment by oschuett** [comment]
I'm having the same problem.

**Comment by wollet42** [comment]
I see the same, any update on this?

All logins are logged but not the failed logins.

Thanks

**Comment by FinishedFragment** [comment]
+1 for this. it is an essential security feature.

**Comment by moisesbr-dw** [comment]
Of course I support this ;-)

@splitbrain please merge my pull request. It's 3 years old already...

**Comment by splitbrain** [comment]
duplicate of #31
