### ISSUE TITLE
Crash my wiki on upgrade to version 2020-10-29 on Release 2018-04-22c "Greebo"

### ISSUE THREAD

**Issue by albion2000** [splitbrain/dokuwiki-plugin-loglog#42]
Upgrading that plugin to version 2020-10-29 (or installing it) on Release 2018-04-22c "Greebo" makes my wiki go Error 500.
Just removing dir lib/plugins/loglog makes the wiki come back to life.
 
theme Bootstrap3
Template v2020-04-04 (develop/20200517)

**Comment by annda** [comment]
Version 2020-11-01 restores backwards compatibility with Greebo.
