### ISSUE TITLE
Logging showing as incorrect date and no username

### ISSUE THREAD

**Issue by acedapig** [splitbrain/dokuwiki-plugin-loglog#45]
Weekly user and admin activity page from admin menu is showing dates as as:

1970/01/01 00:00

All entries are listed at that date

No username is being logged for activities in this page. Can open the loglog.log but that is not easily readable, and not accessible for my general admin users.

**Comment by mais1e** [comment]
Having the same issue here! Reports are great. Log file on webserver is great. Very happy to provide more info!! Thanks for great plugins 👍 

version	Release 2020-07-29 "Hogfather"
conf_template	dokuwiki
os	Linux
webserver	Apache
php_version	7.3.24
php_sapi	cgi-fcgi

**Comment by kjguenther** [comment]
I am having the same issue since updating the plugin. All my entries are stated as 1970/01/01 02:00, with no user name or IP address.

**Comment by annda** [comment]
Thanks for reporting. The bug was introduced in a recent merge and is now fixed in the latest release 2020-11-16.

**Comment by mais1e** [comment]
Amazing! Thanks annda, works beautiful now. Had to reinstall plugin to grab the latest update, works perfect. Thanks so much!
