### ISSUE TITLE
Warning: handle() not implemented 

### ISSUE THREAD

**Issue by MartinSnowden** [splitbrain/dokuwiki-plugin-loglog#47]
Using latest Login/Logoff Logging Plugin version 2020-11-16, with DokuWiki bersion 2020-07-29-0130 (Hogfather)

When I go to "Weekly User and Admin Activity", at the top of the page I get the warning message:

**Warning: handle() not implemented in admin_plugin_loglog in /volume1/web/dokuwiki/lib/plugins/admin.php on line 65**

Sure enough, in that admin.php the code for handle() is:

   **/**
     * Carry out required processing
     */
    public function handle() {
        trigger_error('handle() not implemented in '.get_class($this), E_USER_WARNING);
    }**

While in the admin.php for loglog itself, there is no handle() function at all. Should there not be one? Or I have something messed up here?

**Comment by vettovaglie** [comment]
I have a similar problem, I see the message as a php warning in the apache log.
Maybe in your case is a php setting to show the warning message in the output?

**Comment by splitbrain** [comment]
The handle method is optional in Igor. @vettovaglie are you using Hogfather as well?
