### ISSUE TITLE
farming: loglog.log file from an animal can be viewed without dokuwiki

### ISSUE THREAD

**Issue by farmascript** [splitbrain/dokuwiki-plugin-loglog#50]
farming: loglog.log file from an _animal_ can be viewed without dokuwiki
The content from (for example) http://www.abc.com/animal/def/data/cache/loglog.log is visible in a browser

**Comment by splitbrain** [comment]
your animals should not be within the document root of your farmer. This has nothing to do with the loglog plugin.
